(*---------------------------------------------------------------------------
   Copyright (c) 2025 The webs programmers. All rights reserved.
   SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** WebAuthn passkey authentication.

    This module provides primitives to handle passkeys as your
    authentication mecanism.

    While it makes a few choices on what to expose of that terrible
    mess, it does not prescribe a particular user interface workflow
    or passkey storage. It is only concerned about extracting data
    from the client into proper data structures and provides primitives for
    handling challenges, passkey registrations and verifying client
    provided assertions.

    {b Note.} The support provided by this module is thread-safe.

    {b TODO.}
    {ul
    {- Look the
       {{:https://w3c.github.io/webauthn/#rp-op-verifying-assertion-step-origin}
       cross origin} business of client data. We likely
       want to do something about it in the verifications.}
    {- Write the {!basics}}}

    {b References}.
    {ul
    {- Adam Langley.
       {{:https://www.imperialviolet.org/tourofwebauthn/tourofwebauthn.html}
       A tour of WebAuthn}.}
    {- Editor's draft. {{:https://w3c.github.io/webauthn/}WebAuthn Level 3}.}}
*)

(** Unique, expirable, challenges. *)
module Challenge : sig

  (** {1:validators Validators} *)

  (** Challenge validators.

      A challenge validator ensures passkey challenges are used only
      once and within reasonable time limits. This is an in-memory
      abstraction, if your program crashes or restarts, all challenges
      become invalid.

      In order to bound the amount of memory used by a validator it
      may arbitrarily drop challenges pending verification, see
      {!Validator.max}.  *)
  module Validator : sig

    (** {1:validators Validators} *)

    type now_s = unit -> int
    (** The type for an absolute notion of time in seconds.
        Calling the function must return the current time
        in seconds relative to an arbitrary epoch.

        {b Warning.} The function must be thread-safe. *)

    type 'a t
    (** The type for challenge validators. A value of this type holds
        the state to ensure unique and expirable challenge validation.
        Each challenge can have an associated stored payload of type ['a]. *)

    val make :
      ?max:int -> ?challenge_byte_size:int -> ?challenge_validity_s:int ->
      ?now_s:now_s -> ?crypto_random:Webs_crypto_random.t -> unit -> 'a t
    (** [make ~crypto_random ()] is a challenge validator with:
        {ul
        {- [max] is the maximum number of pending challenges. See {!max}.
           Must be positive or [Invalid_argument] is raised.}
        {- [challenge_byte_size] is the number of random bytes in the
           challenges generated by the validator, defaults to [64]. Must
           be at least [16] or [Invalid_argument] is raised.}
        {- [challenge_validity_s] is the default validity time in [s]
           of challenges. It defaults to 300 seconds (5 minutes)
           as {{:https://w3c.github.io/webauthn/#sctn-timeout-recommended-range}
           recommended}}
        {- [now_s] is a function returning the current time. Defaults
           uses {!Unix.gettimeofday}.}
        {- [crypto_random] is a function returning random bytes of
           cryptographic quality for the challenges. Defaults to
           {!Webs_crypto_random.get}}} *)

    val max : 'a t -> int
    (** [max v] is the maximal number of pending challenges in [v].
        If this number is exceeded on a {!Challenge.make}, an arbitrary
        existing challenge is dropped from the validator. *)

    val challenge_byte_size : 'a t -> int
    (** [challenge_byte_size v] is the number of random bytes in challenges
        generated by [v]. *)

    val challenge_validity_s : 'a t -> int
    (** [challenge_validity_s v] is the default challenge validitiy
        duration of challenges generated by [v]. *)

    val pending : 'a t -> int
    (** [pending v] is the number of challenges pending for validation in
        [v]. *)

    val invalidate_pending : 'a t -> unit
    (** [invalidate_pending v] invalidates all challenges pending for
        validation in [v]. *)
  end

  (** {1:challenges Challenges} *)

  type t
  (** The type for challenges. *)

  val make : ?validity_s:int -> 'a Validator.t -> payload:'a -> t
  (** [make v ~payload] is a new challenge valid for [validity_s]
      seconds with an associated stored payload [payload] stored in
      [v].[validity_s] defaults to {!Validator.challenge_validity_s}[ v]. *)

  val equal : t -> t -> bool
  (** [equal c0 c1] is [true] iff [c0] and [c0] are equal. *)

  val compare : t -> t -> int
  (** [compare] is a total order on challenges compatible with {!equal}. *)

  val validate : 'a Validator.t -> t -> ('a, unit) result
  (** [validate v c] is [Ok playload] if [c] validates with [v] and
      [Error ()] otherwise. [payload] is the value given to {!make}. A
      challenge can be validated only once within the time slot it was
      given at {!make}. Also due to {!Validator.max} it may fail to
      validate earlier. *)

  (** {1:converting Converting} *)

  val to_binary_string : t -> string
  (** [to_binary_string c] are the bytes of the challenge [c]. *)

  val of_binary_string : string -> t
  (** [of_binary_string s] is the challenge from the bytes in [s].

      {b Note.} In practice challenges must be at least [16] bytes
      long. But the only thing you can do with a challenge is {!validate}
      which will fail if that's not the case so we don't check anything here. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats the bytes of the challenge as [base64url]. *)
end

(** Authenticator attestation GUIDs (AAGUID).

    This is mainly for UI purposes. You can match these identifiers
    against a
    {{:https://github.com/passkeydeveloper/passkey-authenticator-aaguids}
    database} to map it to names and icons which helps users to identify
    the source of their passkeys.

    {b TODO.} Should we vendor the db ? *)
module Aaguid : sig
  type t
  (** The type for {{:https://w3c.github.io/webauthn/#aaguid}AAGUID}. *)

  val nil : t
  (** [nil] the {{:https://www.rfc-editor.org/rfc/rfc9562#name-nil-uuid}nil}
      UUID. *)

  val equal : t -> t -> bool
  (** [equal g0 g1] is [true] iff [g0] is equal to [g1]. *)

  val compare : t -> t -> int
  (** [compare] is a total order on credential ids. *)

  val of_binary_string : string -> (t, string) result
  (** [of_binary_string s] is an AAGUID from bytes [s]. Errors if
      [s] has not 16 bytes. *)

  val to_binary_string : t -> string
  (** [to_binary_string gguid] are the bytes of [gguid]. *)

  val to_ascii_uuid : t -> string
  (** [to_ascii_uuid gguid] formats [guuid] to the ASCII representation
      of an {{:https://www.rfc-editor.org/rfc/rfc9562}RFC 9562} UUID. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats AAGGUIDs as ASCII UUIDs for inspection. *)
end

(** Credential IDs. *)
module Credential_id : sig
  type t
  (** The type for {{:https://w3c.github.io/webauthn/#credential-id}
        credential ID}. *)

  val equal : t -> t -> bool
  (** [equal c0 c1] is [true] iff [c0] is equal to [c1]. *)

  val compare : t -> t -> int
  (** [compare] is a total order on credential ids. *)

  val of_binary_string : t -> (t, string) result
  (** [of_binary_string s] is a credential ID from [s]. Errors if
        the length is not between 100 and 1023. *)

  val to_binary_string : t -> string
  (** [to_binary_string cid] are the bytes of credential ID [cid]. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats credentials for inspection using [base64url]. *)
end

(** Public keys. *)
module Public_key : sig

  type algorithm =
  | Es256 (** ECDSA with SHA-256. *)
  | Ed25519 (** EdDSA with Curve25519 and SHA-512 *)
  (** The type for public key algorithms. *)

  type t
  (** The type for public keys. *)

  val make : algorithm -> raw_value:string -> t
  (** [make algo ~value] is ay key with given algorithm and raw binary
      key value. *)

  val algorithm : t -> algorithm
  (** [algorithm k] is the algorithm of [k]. *)

  val raw_value : t -> string
  (** [raw_value k] is the raw binary key value. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats a public key for inspection. *)
end

(** Passkeys (client provided public keys).

    These need to be stored and associated to your users. *)
module Passkey : sig

  type t
  (** The type for passkeys. *)

  val make :
    aaguid:Aaguid.t -> credential_id:Credential_id.t ->
    public_key:Public_key.t -> unit -> t
  (** [make aaguid ~credential ~public_key ()] is a passkey with given
      parameters. See accessors for semantics. *)

  val aaguid : t -> Aaguid.t
  (** [aaguid pk] is the {{:https://w3c.github.io/webauthn/#aaguid}AAGUID}
       of the authenticator that created [pk]. *)

  val credential_id : t -> Credential_id.t
  (** [credential_id pk] is the
      {{:https://w3c.github.io/webauthn/#credential-id} credential ID}
      assigned by the authenticator to [pk]. *)

  val public_key : t -> Public_key.t
  (** [public_key pk] is the public key of [pk]. *)

  (** {1:converting Converting} *)

  val of_public_key : Public_key.t -> t
  (** [of_public_key pk] is a passkey with the given public key. All
      other fields are zeroed out but this is enough to give to
      {!Webs_passkey.verify}. *)

  (** {1:fmt Formatting} *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats a passkey for inspection. *)
end

(** Registrations (client passkey registration). *)
module Registration : sig
  type t
  (** The type for client passkey registration. *)

  val of_public_key_credential_json : string -> (t, string) result
  (** [of_public_key_credential_json s] decodes a registration from the
      {{:https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/toJSON}JSON
      serialization} of a
      {{:https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential}
      [PublicKeyCredential]} with an
      {{:https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse}[AuthenticatorAttestationResponse]} [response] member.
      Typically, the result of a response of a call to
      {{:https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create}[navigator.credential.create]}. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats a registration for inspection. *)
end

(** Assertions (client signed challenges). *)
module Assertion : sig
  type t
  (** The type for assertions. *)

  val credential_id : t -> Credential_id.t
  (** [credential_id a] is the credential that signed the assertion. *)

  val of_public_key_credential_json : string -> (t, string) result
  (** [of_public_key_credential_json s] decodes an assertion from the
      {{:https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/toJSON}JSON serialization} of a
      {{:https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential}
      [PublicKeyCredential]} with an
      {{:https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse}[AuthenticatorAssertionResponse]} [response] member.
      Typically, the result of a response of a call to
      {{:https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get}[navigator.credential.get]}. *)

  val pp : Format.formatter -> t -> unit
  (** [pp] formats an assertion for inspection. *)
end

(** Relying party (registers and verifies client assertions). *)
module Relying_party : sig
  type id = string
  (** The type for {{:https://w3c.github.io/webauthn/#relying-party-identifier}
      relying part identifiers}. Basically your domain name. *)

  type 'a t
  (** The type for relying parties with challenge payloads of type
      ['a]. *)

  val make :
    ?challenge_validator:'a Challenge.Validator.t -> id:id -> unit -> 'a t
  (** [make ~id ()] is a relying party with id [id] using
      [challenge_validator] to generate and validate challenges
      (defaults to {!Challenge.Validator.make}[ ()]). *)
end

(** {1:register Register and verify passkeys} *)

type error =
| Invalid_relying_party_origin of { found : string; expected : string }
| Invalid_relying_party_hash of { found : Bytesrw_crypto.Sha_256.t;
                                  expected : Bytesrw_crypto.Sha_256.t }
| Invalid_client_data_type of { found : string; expected : string }
| Invalid_challenge of Challenge.t
| Invalid_signature of { signature : string (** binary *); msg : string } (** *)
(** The type for operation errors. *)

val error_message : error -> string
(** [error_message e] is an error message for [e]. *)

val challenge :
  ?validity_s:int -> 'a Relying_party.t -> payload:'a -> Challenge.t
(** [challenge rp] is a challenge generated by [rp]. Note this library
    also uses a challenge for {!val-register}. *)

val register :
  'a Relying_party.t -> Registration.t -> ('a * Passkey.t, error) result
(** [register rp r] registers a new passkey from registration data [r].
    This verifies that (and only that), in order:
    {ol
    {- The client data's [type] is [webauth.create]}
    {- The client data's origin matches the relying party identifier of [rp].}
    {- The authenticator data SHA-256 hash of the relying party identifier
       is the one of [rp].}
    {- The authenticator SHA-256 hash of the relying party identifier
       is correct.}
    {- The challenge still exists and was never used.}
    {- The registration's origin and relying party identifier
       matches the one in [rp]}} *)

val verify :
  'a Relying_party.t -> Passkey.t -> Assertion.t -> ('a, error) result
(** [verify rp pub_key assertion] is  [Ok ()] if [assertion]
    is validated by [pub_key] and [a]. This verifies that (and only that),
    in order:
    {ol
    {- The client data's [type] is [webauth.get]}
    {- The client data's origin matches the relying party identifier of [rp].}
    {- The authenticator data SHA-256 hash of the relying party identifier
       is the one of [rp].}
    {- The assertion signature is verified by the public key of [pub_key].}
    {- The challenge still exists and was never used.}}

    {b Note.} It is your duty to find out which [pub_key] must be used to
    validate [assertion], by looking them up somewhere via
    {!Assertion.credential_id}. Note that formally only the
    {!Passkey.val-public_key} field is needed to perform the check, the
    rest is metadata. you can use {!Passkey.of_public_key} if that's
    the only thing you have. *)

(** {1:basics Basics}

    TODO meanwhile checkout
    {{:https://github.com/dbuenzli/webs/tree/master/test/passkey.ml}
    this example}.

    - Create a relying party representing your website
    - Handle passkey registrations.
    - Verify passkeys. *)
